name: Deploying stage

on:
  pull_request:
    branches:
      - main
jobs:

  server_ci_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone repository
        uses: actions/checkout@v1
      - name: Create and populate .env file
        run: |
          touch .env
          echo aws_host="124" >> .env
          echo aws_port="1234" >> .env
          echo aws_pw="werwer" >> .env
          echo aws_user="werwer" >> .env
          echo dbname="erwerw" >> .env

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
         aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
         aws-region: us-east-1

      - name: Deploy Client Application to S3 bucket
        working-directory: .
        run: aws s3 sync . s3://testenvtest --delete
